# Generated by Django 5.2.9 on 2026-01-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20191114_2202'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='products_pr_id_a08e3c_idx',
            old_fields=('id', 'slug'),
        ),
    ]
